PPal-Ajo/WashPlan

src/main/resources/static/css/base/nav.css, src/main/resources/templates/base/nav.html
Nav FrontEnd 작성
<br/>
#1 
<br/>
네브 프론트엔드 작업
<br/>
<br/>
=> [FEATURE][NavFrontEnd]Nav 프론트엔드 

src/main/java/com/ohgiraffers/washplan/auth/controller/AuthController.java, src/main/java/com/ohgiraffers/washplan/auth/model/service/AuthService.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/dto/UserDTO.java, src/main/resources/mappers/UserMapper.xml
이제 커스텀로그인 화면으로 넘어가집니다
<br/>
#11 
<br/>
<br/>
<br/>
=> [FEATURE][LOGINSECURITY]로그인/메인 시큐리티

src/main/java/com/ohgiraffers/washplan/auth/controller/AuthController.java, src/main/java/com/ohgiraffers/washplan/auth/model/service/AuthService.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/dto/UserDTO.java, src/main/resources/mappers/UserMapper.xml, src/main/resources/static/css/auth/login.css, src/main/resources/templates/auth/login.html
아이디랑 비밀번호 틀렷다는 에러메세지만 뜨고 메인페이지로 안넘어갑니다
<br/>
#15 
<br/>
<br/>
<br/>
=> [FEATURE][LOGINTEST] 로그인 테스트

src/main/resources/static/css/signup/email.css, src/main/resources/templates/signup/email.html
이메일 인증 프론트입니다
<br/>
#19 
<br/>
<br/>
<br/>
=> [FEATURE][EMAILFRONT]이메일 인증 화면

build.gradle, src/main/java/com/ohgiraffers/washplan/auth/controller/EmailController.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/resources/static/css/signup/email.css, src/main/resources/templates/signup/email.html
이메일인증시 인증번호 기능
<br/>
<br/>
<br/>
<br/>
=> [FEATURE][EMAILSEND]이메일인증 메일 보내기

build.gradle, src/main/java/com/ohgiraffers/washplan/auth/controller/CodeData.java, src/main/java/com/ohgiraffers/washplan/auth/controller/EmailController.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/service/UserService.java, src/main/resources/static/css/signup/email.css, src/main/resources/templates/auth/login.html, src/main/resources/templates/signup/email.html
이메일, 인증번호 유효성검사 인증완료 후 모달창
<br/>
<br/>
<br/>
<br/>
=> [FEATURE][EMAILCHECK]이메일 인증 유효성검사 / 모달

src/main/java/com/ohgiraffers/washplan/auth/controller/AuthController.java, src/main/java/com/ohgiraffers/washplan/auth/controller/EmailController.java, src/main/java/com/ohgiraffers/washplan/auth/controller/SignupController.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/resources/static/css/signup/signup.css, src/main/resources/templates/signup/email.html, src/main/resources/templates/signup/signup.html
이제 인증받은 이메일이 자동으로 회원가입 이메일 칸에 들어갑니다.
<br/>
#32 
<br/>
<br/>
<br/>
=> [FEATURE][SIGNUPINSERT]이메일-회원가입 연동

src/main/java/com/ohgiraffers/washplan/reservation/controller/ReservationController.java, src/main/java/com/ohgiraffers/washplan/reservation/model/dao/ReservationMapper.java, src/main/java/com/ohgiraffers/washplan/reservation/model/dto/ReservationDTO.java, src/main/java/com/ohgiraffers/washplan/reservation/model/service/ReservationService.java, src/main/resources/mappers/ReservationMapper.xml, src/main/resources/static/css/reservation/reservation.css, src/main/resources/templates/reservation/reservation.html
유저가 선택한 날짜와 시간대에 예약을 하면 그 날짜와 그 시간대만 예약중으로 바뀌고 다른곳은 사용가능으로 나옵니다.
<br/>
#29 
<br/>
<br/>
<br/>
=> [FEATURE][RESERVATION-STATUS-DB] 예약현황 DB 연동

src/main/java/com/ohgiraffers/washplan/auth/controller/AuthSignupController.java, src/main/java/com/ohgiraffers/washplan/user/controller/SignupController.java, src/main/java/com/ohgiraffers/washplan/user/controller/UserSignupController.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/dto/UserDTO.java, src/main/resources/mappers/UserMapper.xml, src/main/resources/templates/signup/signup.html
이제 회원가입이 작동을 합니다
<br/>
<br/>
<br/>
<br/>
=> [FEATURE][SIGNUPINSERT]회원가입 가입 

src/main/java/com/ohgiraffers/washplan/auth/controller/AuthSignupController.java, src/main/java/com/ohgiraffers/washplan/auth/model/dao/AuthMapper.java, src/main/java/com/ohgiraffers/washplan/auth/model/dto/CustomUserDetails.java, src/main/java/com/ohgiraffers/washplan/auth/model/service/AuthService.java, src/main/java/com/ohgiraffers/washplan/auth/model/service/CustomUserDetailsService.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/java/com/ohgiraffers/washplan/user/controller/SignupController.java, src/main/java/com/ohgiraffers/washplan/user/controller/UserSignupController.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/dto/UserDTO.java, src/main/resources/mappers/UserMapper.xml, src/main/resources/templates/signup/signup.html
회원가입시 디비에 토큰화되어있습니다. 아직 로그인 기능은 안됩니다
<br/>
<br/>
<br/>
<br/>
=> [FEATURE][PWDTOKEN]회원가입 패스워드 토큰화

src/main/java/com/ohgiraffers/washplan/auth/model/dao/AuthMapper.java, src/main/java/com/ohgiraffers/washplan/auth/model/service/CustomUserDetailsService.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/dto/UserDTO.java, src/main/resources/mappers/UserMapper.xml, src/main/resources/static/css/base/nav.css, src/main/resources/templates/main/main.html
이제 db에 있는 아이디로 로그인, 메인페이지에서 로그아웃 가능합니다
<br/>
#40 
<br/>
<br/>
<br/>
=> [FEATURE][LOGINACTIVE]로그인 기능

src/main/java/com/ohgiraffers/washplan/auth/model/dao/AuthMapper.java, src/main/java/com/ohgiraffers/washplan/auth/model/service/AuthService.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/java/com/ohgiraffers/washplan/user/controller/UserController.java, src/main/java/com/ohgiraffers/washplan/user/controller/UserSignupController.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/service/UserService.java, src/main/resources/mappers/UserMapper.xml, src/main/resources/static/css/signup/signup.css, src/main/resources/templates/signup/signup.html
회원가입 유효성검사 잘되고 완료될시 모달창 까지 표시
<br/>
#42 
<br/>
<br/>
<br/>
=> [FEATURE][SIGNUPVALID]회원가입 유효성검사

src/main/java/com/ohgiraffers/washplan/admin/controller/AdminController.java, src/main/java/com/ohgiraffers/washplan/admin/model/dao/AdminMapper.java, src/main/java/com/ohgiraffers/washplan/admin/model/dto/AdminDTO.java, src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/java/com/ohgiraffers/washplan/auth/model/dto/CustomUserDetails.java, src/main/java/com/ohgiraffers/washplan/auth/model/service/CustomUserDetailsService.java, src/main/java/com/ohgiraffers/washplan/reservation/controller/ReservationController.java, src/main/java/com/ohgiraffers/washplan/user/model/dto/UserDTO.java, src/main/resources/mappers/AdminMapper.xml, src/main/resources/mappers/UserMapper.xml, src/main/resources/static/css/admin/admin.css, src/main/resources/static/css/admin/adminUser.css, src/main/resources/templates/admin/adminUser.html
로그인한 유저 넘버 가져오기 성공하였고 사용자관리 회원조회와 일시정지, 영구탈퇴 버튼 누르면 수정되도록 하였습니다.
<br/>
#43 
<br/>
<br/>
<br/>
=> [FEATURE][LOGIN-USERNO-DB] 로그인한 유저넘버 가져오기

src/main/resources/static/css/auth/login.css, src/main/resources/templates/auth/login.html, src/main/resources/templates/signup/signup.html
비밀번호 입력칸 오른쪽에있는 이미지를 누르면 비밀번호가 표시/미표시 됩니다.
<br/>
#46 
<br/>
<br/>
<br/>
=> [FEATURE][PWDSEEHIDE]비밀번호 표시/미표시

src/main/java/com/ohgiraffers/washplan/admin/controller/AdminController.java, src/main/java/com/ohgiraffers/washplan/admin/model/dao/AdminMapper.java, src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/resources/mappers/AdminMapper.xml, src/main/resources/static/css/admin/adminUser.css, src/main/resources/templates/admin/admin.html, src/main/resources/templates/admin/adminuser.html
사용자 관리 검색기능 구현하였습니다
<br/>
#47 
<br/>
<br/>
<br/>
=> [FEATURE][ADMIN-SEARCH] 사용자관리 검색기능

src/main/java/com/ohgiraffers/washplan/auth/controller/AuthSignupController.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/resources/static/css/auth/forget.css, src/main/resources/templates/auth/forget.html, src/main/resources/templates/auth/login.html
아이디/비밀번호찾기 프론트화면
<br/>
#49 
<br/>
<br/>
<br/>
=> [FEATURE][FINDIDPWD]아이디/비밀번호 찾기 페이지

src/main/java/com/ohgiraffers/washplan/auth/controller/AuthSignupController.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/resources/static/css/auth/findid.css, src/main/resources/static/css/auth/forget.css, src/main/resources/templates/auth/findid.html, src/main/resources/templates/auth/forget.html, src/main/resources/templates/auth/login.html
아이디찾기 화면 구상입니다
<br/>
#55 
<br/>
<br/>
<br/>
=> [FEATURE][FINDIDFRONT]아이디찾기 화면

src/main/java/com/ohgiraffers/washplan/auth/controller/AuthSignupController.java, src/main/java/com/ohgiraffers/washplan/auth/controller/EmailController.java, src/main/java/com/ohgiraffers/washplan/auth/controller/FindEmailController.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/service/UserService.java, src/main/resources/static/css/auth/findid.css, src/main/resources/static/css/auth/forget.css, src/main/resources/templates/auth/findid.html, src/main/resources/templates/auth/forget.html, src/main/resources/templates/auth/login.html
아이디찾기 정상적으로 작동합니다
<br/>
#57 
<br/>
<br/>
<br/>
=> [FEATURE][FINDID]아이디찾기 기능

src/main/java/com/ohgiraffers/washplan/admin/controller/AdminController.java, src/main/java/com/ohgiraffers/washplan/admin/model/dao/AdminMapper.java, src/main/java/com/ohgiraffers/washplan/admin/model/dto/MachineDTO.java, src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/resources/mappers/AdminMapper.xml, src/main/resources/static/css/admin/adminMachine.css, src/main/resources/static/css/reservation/reservation.css, src/main/resources/templates/admin/adminmachine.html, src/main/resources/templates/reservation/reservation.html
기기관리 DB 연동하기
<br/>
#53 
<br/>
<br/>
<br/>
=> [FEATURE][ADMIN-MACHINE-DB] 기기관리 DB 연동

src/main/java/com/ohgiraffers/washplan/auth/controller/AuthSignupController.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/resources/static/css/auth/findpwd.css, src/main/resources/static/css/auth/forget.css, src/main/resources/templates/auth/findpwd.html, src/main/resources/templates/auth/forget.html
비밀번호찾기 화면 구상
<br/>
#60 
<br/>
<br/>
스크린샷) 🖼
<br/>
=> [FEATURE][FINDPWDFRONT]비밀번호 찾기 화면

src/main/resources/static/css/admin/adminInquiry.css, src/main/resources/templates/admin/admininquiry.html
문의관리 화면구현 하였습니다
<br/>
#61 
<br/>
<br/>
<br/>
=> [FEATURE][ADMIN-INQUIRY-FRONT] 문의관리 화면구현

src/main/java/com/ohgiraffers/washplan/auth/controller/AuthController.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/service/UserService.java, src/main/resources/static/css/auth/findpwd.css, src/main/resources/templates/auth/findpwd.html
비밀번호 찾기할때 이메일과 아이디가 일치하지않으면 다음버튼 비활성화
<br/>
#63 
<br/>
<br/>
<br/>
=> [FEATURE][CHECKVALID]비밀번호 찾기 유효성검사

src/main/java/com/ohgiraffers/washplan/admin/controller/AdminController.java, src/main/java/com/ohgiraffers/washplan/admin/model/dao/AdminMapper.java, src/main/java/com/ohgiraffers/washplan/admin/model/dto/AdminInquiryDTO.java, src/main/java/com/ohgiraffers/washplan/admin/model/dto/AdminMachineDTO.java, src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/resources/mappers/AdminMapper.xml, src/main/resources/static/css/admin/adminInquiry.css, src/main/resources/static/css/admin/adminMachine.css, src/main/resources/templates/admin/admin.html, src/main/resources/templates/admin/admininquiry.html, src/main/resources/templates/admin/adminmachine.html, src/main/resources/templates/admin/adminuser.html
문의 내역 DB 연동 했습니다
<br/>
#65 
<br/>
<br/>
<br/>
=> [FEATURE][ADMIN-INQUIRY-DB] 문의관리 DB연동

src/main/java/com/ohgiraffers/washplan/auth/controller/AuthController.java, src/main/java/com/ohgiraffers/washplan/auth/controller/AuthSignupController.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/service/UserService.java, src/main/resources/static/css/auth/findpwd.css, src/main/resources/static/css/auth/reset.css, src/main/resources/templates/auth/findpwd.html, src/main/resources/templates/auth/reset.html
비밀번호 재설정 화면입니다
<br/>
<br/>
<br/>
<br/>
=> [FEATURE][RESETPWDFRONT]비밀번호 재설정 화면

src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/resources/static/css/admin/adminInquiry.css, src/main/resources/templates/admin/admininquiry.html
문의 내역 페이징 처리 하였습니다.
<br/>
#69
<br/>
<br/>
<br/>
=> [FEATURE][ADMIN-INQUIRY-PAGE] 문의관리 페이징 처리

src/main/java/com/ohgiraffers/washplan/auth/controller/AuthController.java, src/main/java/com/ohgiraffers/washplan/auth/controller/AuthSignupController.java, src/main/java/com/ohgiraffers/washplan/auth/model/dao/AuthMapper.java, src/main/java/com/ohgiraffers/washplan/auth/model/service/AuthService.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/service/UserService.java, src/main/resources/templates/auth/reset.html
비밀번호 재설정 기능입니다
<br/>
#71
<br/>
<br/>
<br/>
=> [FEATURE][RESETPWD]비밀번호 재설정

src/main/java/com/ohgiraffers/washplan/admin/controller/AdminController.java, src/main/java/com/ohgiraffers/washplan/admin/model/dao/AdminMapper.java, src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/resources/mappers/AdminMapper.xml, src/main/resources/templates/admin/admininquiry.html, src/main/resources/templates/admin/adminuser.html
문의 관리 검색기능 구현하였습니다~
<br/>
#73 
<br/>
<br/>
<br/>
=> [FEATURE][ADMIN-INQUIRY-SEARCH] 문의관리 검색기능

src/main/resources/static/css/auth/reset.css, src/main/resources/templates/auth/reset.html
비밀번호 재설정할 때 유효성검사를 하고 완료할시 모달창이 뜨도록 수정
<br/>
#75 
<br/>
<br/>
<br/>
=> [FEATURE][RESETPWDVALID]비밀번호 재설정 유효성 모달추가

src/main/java/com/ohgiraffers/washplan/admin/controller/AdminController.java, src/main/java/com/ohgiraffers/washplan/admin/model/dao/AdminMapper.java, src/main/java/com/ohgiraffers/washplan/admin/model/dto/AdminInquiryDTO.java, src/main/java/com/ohgiraffers/washplan/admin/model/dto/AdminInquiryReplyDTO.java, src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/resources/mappers/AdminMapper.xml, src/main/resources/static/css/admin/adminInquiry.css, src/main/resources/templates/admin/admininquiry.html
문의 관리 상세조회 구현하였고 답변하면 DB에 연동 되도록 구현하였습니다!
<br/>
#77 
<br/>
<br/>
<br/>
=> [FEATURE][ADMIN-INQUIRY-DETAILS] 문의관리 상세조회

src/main/java/com/ohgiraffers/washplan/admin/model/dto/AdminAuthDTO.java, src/main/java/com/ohgiraffers/washplan/auth/model/dao/AuthMapper.java, src/main/java/com/ohgiraffers/washplan/auth/model/dto/CustomUserDetails.java, src/main/java/com/ohgiraffers/washplan/auth/model/service/CustomUserDetailsService.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/resources/templates/admin/admin.html
이제 유저가 로그인하면 메인페이지로 관리자가 로그인하면 관리자페이지로 가집니다.
<br/>
#79 
<br/>
<br/>
<br/>
=> [FEATURE][SECURITYROLE] 시큐리티 역할 설정

src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/resources/templates/main/main.html
이제 홈페이지 접근할때 메인페이지가 먼저 뜨고, 로그인 하였을때 마이페이지/ 로그아웃이 출력됩니다
<br/>
#83
<br/>
<br/>
<br/>
=> [FEATURE][MAINREDIRECT]메인페이지 리다이렉트

src/main/java/com/ohgiraffers/washplan/admin/controller/AdminController.java, src/main/resources/static/css/admin/admin.css, src/main/resources/static/css/admin/adminInquiry.css, src/main/resources/static/css/admin/adminMachine.css, src/main/resources/static/css/admin/adminNotice.css, src/main/resources/templates/admin/admin.html, src/main/resources/templates/admin/admininquiry.html, src/main/resources/templates/admin/adminmachine.html, src/main/resources/templates/admin/adminnotice.html, src/main/resources/templates/admin/adminuser.html
공지사항 관리 화면 구현하였습니다~
<br/>
#81 
<br/>
<br/>
<br/>
=> [FEATURE][ADMIN-NOTICE-FRONT] 공지사항관리 화면 구현

src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/resources/templates/main/main.html
비회원 / 회원 일시 보이는 nav가 다릅니다.
<br/>
#83
<br/>
<br/>
<br/>
=> [FEATURE][MAINREDIRECT]메인페이지 상태 변경

src/main/java/com/ohgiraffers/washplan/admin/controller/AdminController.java, src/main/java/com/ohgiraffers/washplan/admin/model/dao/AdminMapper.java, src/main/java/com/ohgiraffers/washplan/admin/model/dto/AdminNoticeDTO.java, src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/resources/mappers/AdminMapper.xml, src/main/resources/templates/admin/adminnotice.html
공지관리 작성 구현입니다.
<br/>
#93 
<br/>
<br/>
<br/>
=> [FEATURE][ADMIN-NOTICE-WRITE] 공지관리 작성 구현

src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/resources/mappers/UserMapper.xml, src/main/resources/static/css/mypage/mypage.css, src/main/resources/templates/mypage/mypage.html
마이페이지에서 비밀번호 수정이 가능합니다
<br/>
#94 
<br/>
<br/>
<br/>
=> [FEATURE][MYPAGEUPDATE]마이페이지 비밀번호 수정

src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/MyPageMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/service/MyPageService.java, src/main/java/com/ohgiraffers/washplan/user/model/service/UserService.java, src/main/resources/mappers/MyPageMapper.xml, src/main/resources/static/css/mypage/mypage.css, src/main/resources/templates/mypage/mypage.html
마이페이지에서 회원탈퇴 가능합니다 아직 모달으로 구현 X
<br/>
#98 
<br/>
<br/>
<br/>
=> [FEATURE][SECESSION]회원탈퇴 

src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/MyPageMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/service/MyPageService.java, src/main/java/com/ohgiraffers/washplan/user/model/service/UserService.java, src/main/resources/mappers/MyPageMapper.xml, src/main/resources/static/css/mypage/mypage.css, src/main/resources/templates/mypage/mypage.html
마이페이지에서 회원탈퇴를 하였을때 알럿이아닌 모달로 뜨게 수정
<br/>
#100
<br/>
<br/>
<br/>
=> [FEATURE][SECESSION-MODAL]회원탈퇴 모달

src/main/java/com/ohgiraffers/washplan/admin/controller/AdminController.java, src/main/java/com/ohgiraffers/washplan/admin/model/dao/AdminMapper.java, src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/resources/mappers/AdminMapper.xml, src/main/resources/static/css/admin/adminNotice.css, src/main/resources/templates/admin/adminnotice.html
공지사항 상세조회 및 수정 구현하였습니다~
<br/>
#97 
<br/>
<br/>
<br/>
=> [FEATURE][ADMIN-NOTICE-DETAILS-UPDATE] 공지 관리 상세조회 수정

src/main/java/com/ohgiraffers/washplan/reservation/model/dao/ReservationMapper.java, src/main/java/com/ohgiraffers/washplan/reservation/model/service/ReservationService.java, src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/MyPageMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/dto/ReservationDetailsDTO.java, src/main/java/com/ohgiraffers/washplan/user/model/service/MyPageService.java, src/main/resources/mappers/MyPageMapper.xml, src/main/resources/mappers/ReservationMapper.xml, src/main/resources/static/css/mypage/mypage.css, src/main/resources/static/css/mypage/reservation.css, src/main/resources/templates/mypage/mypage.html, src/main/resources/templates/mypage/reservation.html
예약현황 데이터베이스 연결
<br/>
#106 
<br/>
<br/>
<br/>
=> [FEATURE][RESERVATIONCHECK]예약현황 연결

build.gradle, src/main/java/com/ohgiraffers/washplan/admin/model/dao/AdminMapper.java, src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/java/com/ohgiraffers/washplan/auth/model/service/CustomUserDetailsService.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/java/com/ohgiraffers/washplan/reservation/controller/ReservationController.java, src/main/java/com/ohgiraffers/washplan/reservation/model/dto/ReservationDTO.java, src/main/java/com/ohgiraffers/washplan/reservation/model/service/QRCodeService.java, src/main/resources/mappers/AdminMapper.xml, src/main/resources/mappers/ReservationMapper.xml, src/main/resources/static/css/auth/login.css, src/main/resources/static/css/main/main.css, src/main/resources/static/css/reservation/reservation.css, src/main/resources/templates/admin/adminuser.html, src/main/resources/templates/auth/login.html, src/main/resources/templates/main/main.html, src/main/resources/templates/reservation/reservation.html
유저 관리 패널티 기능 구현
<br/>
#104 
<br/>
<br/>
<br/>
=> [FEATURE][ADMIN-USER-PENALTY] 유저관리 페널티

src/main/java/com/ohgiraffers/washplan/reservation/model/dao/ReservationMapper.java, src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/MyPageMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/dto/ReservationDetailsDTO.java, src/main/java/com/ohgiraffers/washplan/user/model/service/MyPageService.java, src/main/resources/mappers/MyPageMapper.xml, src/main/resources/templates/mypage/reservation.html
예약취소 기능 
<br/>
#108 
<br/>
<br/>
<br/>
=> [FEATURE][RESERVATIONDELETE]예약취소 기능

src/main/java/com/ohgiraffers/washplan/reservation/model/dao/ReservationMapper.java, src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/MyPageMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/dto/ReservationDetailsDTO.java, src/main/java/com/ohgiraffers/washplan/user/model/service/MyPageService.java, src/main/resources/mappers/MyPageMapper.xml, src/main/resources/static/css/mypage/reservation.css, src/main/resources/templates/mypage/reservation.html
예약삭제를 알림에서 모달로 변경
<br/>
#112
<br/>
<br/>
<br/>
=> [FEATURE][RESERVATIONDELETEMODAL]예약삭제 모달화

src/main/java/com/ohgiraffers/washplan/reservation/controller/ReservationController.java, src/main/java/com/ohgiraffers/washplan/reservation/model/dao/ReservationMapper.java, src/main/java/com/ohgiraffers/washplan/reservation/model/dto/ReservationDTO.java, src/main/java/com/ohgiraffers/washplan/reservation/model/service/ReservationService.java, src/main/resources/mappers/ReservationMapper.xml, src/main/resources/templates/reservation/reservation.html
예약 할시 예약 정보가 담긴 QR코드가 이미지로 화면에 나오고 DB에 저장 되게 구현했습니다.
<br/>
#110 
<br/>
<br/>
<br/>
=> [FEATURE][RESERVATION-QRCODE] QR코드 기능

src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/resources/static/css/mypage/inquiry.css, src/main/resources/templates/mypage/inquiry.html, src/main/resources/templates/mypage/mypage.html, src/main/resources/templates/mypage/reservation.html
마이페이지-예약현황 화면 구상
<br/>
#114
<br/>
<br/>
<br/>
=> [FEATURE][INQUIRYDETAILFRONT]예약현황화면 

src/main/java/com/ohgiraffers/washplan/inquiry/controller/InquiryController.java, src/main/java/com/ohgiraffers/washplan/inquiry/model/dao/InquiryMapper.java, src/main/java/com/ohgiraffers/washplan/inquiry/model/service/InquiryService.java, src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/resources/mappers/InquiryMapper.xml, src/main/resources/static/css/faq/faq.css, src/main/resources/static/css/mypage/inquiry.css, src/main/resources/templates/faq/faq.html, src/main/resources/templates/mypage/inquiry.html
마이페이지에서 나의문의내역을 볼수있습니다
<br/>
#127 
<br/>
<br/>
<br/>
=> [FEAUTRE][MYPAGEMYINQUIRY]마이페이지 나의문의내역

src/main/java/com/ohgiraffers/washplan/inquiry/controller/InquiryController.java, src/main/java/com/ohgiraffers/washplan/inquiry/model/dao/InquiryMapper.java, src/main/java/com/ohgiraffers/washplan/inquiry/model/dto/InquiryDTO.java, src/main/java/com/ohgiraffers/washplan/inquiry/model/service/InquiryService.java, src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/resources/mappers/InquiryMapper.xml, src/main/resources/static/css/faq/faq.css, src/main/resources/static/css/mypage/inquiry.css, src/main/resources/templates/faq/faq.html, src/main/resources/templates/mypage/inquiry.html
나의문의를 상세조회 할수 있습니다.
<br/>
#131
<br/>
<br/>
<br/>
=> [FEATURE][MYINQUIRYDETAIL]나의문의 상세조회

src/main/java/com/ohgiraffers/washplan/inquiry/controller/InquiryController.java, src/main/java/com/ohgiraffers/washplan/inquiry/model/dao/InquiryMapper.java, src/main/java/com/ohgiraffers/washplan/inquiry/model/dto/InquiryDTO.java, src/main/java/com/ohgiraffers/washplan/inquiry/model/service/InquiryService.java, src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/resources/mappers/InquiryMapper.xml, src/main/resources/static/css/faq/faq.css, src/main/resources/static/css/mypage/inquiry.css, src/main/resources/templates/faq/faq.html, src/main/resources/templates/mypage/inquiry.html
마이페이지 나의 문의내역에서 삭제 가능
<br/>
#133 
<br/>
<br/>
<br/>
=> [FEATURE][MYINQUIRYDELETE]나의 문의내역 삭제

src/main/java/com/ohgiraffers/washplan/inquiry/controller/InquiryController.java, src/main/java/com/ohgiraffers/washplan/inquiry/model/dao/InquiryMapper.java, src/main/java/com/ohgiraffers/washplan/inquiry/model/dto/InquiryDTO.java, src/main/java/com/ohgiraffers/washplan/inquiry/model/service/InquiryService.java, src/main/java/com/ohgiraffers/washplan/notice/controller/NoticeController.java, src/main/java/com/ohgiraffers/washplan/notice/model/dao/NoticeMapper.java, src/main/java/com/ohgiraffers/washplan/notice/model/dto/NoticeDTO.java, src/main/java/com/ohgiraffers/washplan/notice/model/service/NoticeService.java, src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/resources/mappers/InquiryMapper.xml, src/main/resources/mappers/NoticeMapper.xml, src/main/resources/static/css/faq/faq.css, src/main/resources/static/css/faq/notice.css, src/main/resources/static/css/mypage/inquiry.css, src/main/resources/templates/faq/faq.html, src/main/resources/templates/faq/notice.html, src/main/resources/templates/mypage/inquiry.html
공지사항 전체조회 가능
<br/>
#135
<br/>
<br/>
<br/>
=> [FEATURE][NOTICEFRONT] 공지사항 전체조회

src/main/java/com/ohgiraffers/washplan/admin/controller/AdminController.java, src/main/java/com/ohgiraffers/washplan/admin/model/dao/AdminMapper.java, src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/resources/mappers/AdminMapper.xml, src/main/resources/static/css/admin/admin.css, src/main/resources/static/css/admin/adminInquiry.css, src/main/resources/static/css/admin/adminMachine.css, src/main/resources/static/css/admin/adminNotice.css, src/main/resources/static/css/admin/adminUser.css, src/main/resources/templates/admin/admin.html, src/main/resources/templates/admin/admininquiry.html, src/main/resources/templates/admin/adminmachine.html, src/main/resources/templates/admin/adminnotice.html, src/main/resources/templates/admin/adminuser.html
기기 삭제 기능 구현하였습니다
<br/>
#139 
<br/>
<br/>
<br/>
=> [FEATURE][MACHINE-DELETE] 기기 삭제

src/main/java/com/ohgiraffers/washplan/notice/controller/NoticeController.java, src/main/java/com/ohgiraffers/washplan/notice/model/dao/NoticeMapper.java, src/main/java/com/ohgiraffers/washplan/notice/model/service/NoticeService.java, src/main/java/com/ohgiraffers/washplan/reservation/model/service/ReservationService.java, src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/MyPageMapper.java, src/main/java/com/ohgiraffers/washplan/user/model/service/MyPageService.java, src/main/resources/mappers/MyPageMapper.xml, src/main/resources/mappers/NoticeMapper.xml, src/main/resources/static/css/faq/notice.css, src/main/resources/static/css/mypage/reservation.css, src/main/resources/templates/faq/notice.html
예약현황 페이지에서 QR버튼 누를시 코드확인
<br/>
<br/>
<br/>
<br/>
=> [FEATURE][MYRESERVATIONQR]예약현황 QR

src/main/resources/templates/auth/findid.html, src/main/resources/templates/auth/findpwd.html, src/main/resources/templates/auth/forget.html, src/main/resources/templates/auth/login.html, src/main/resources/templates/auth/reset.html, src/main/resources/templates/faq/faq.html, src/main/resources/templates/faq/notice.html, src/main/resources/templates/mypage/inquiry.html, src/main/resources/templates/mypage/mypage.html, src/main/resources/templates/mypage/reservation.html, src/main/resources/templates/reservation/reservation.html, src/main/resources/templates/signup/agree.html, src/main/resources/templates/signup/email.html, src/main/resources/templates/signup/signup.html
nav 연동 되도록 설정
<br/>
#144
<br/>
<br/>
<br/>
=> [FEATURE][NAVMODIFY]nav 수정

src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/resources/static/css/faq/notice.css, src/main/resources/static/css/mypage/inquiry.css, src/main/resources/static/css/mypage/reservation.css, src/main/resources/templates/faq/notice.html, src/main/resources/templates/main/main.html, src/main/resources/templates/mypage/inquiry.html
전체적인 수정
<br/>
#150
<br/>
<br/>
<br/>
=> [FIX][FIXOVERALL]전체적인 수정

src/main/java/com/ohgiraffers/washplan/config/CustomErrorController.java, src/main/java/com/ohgiraffers/washplan/user/model/dao/UserMapper.java, src/main/resources/static/css/faq/notice.css, src/main/resources/static/css/mypage/inquiry.css, src/main/resources/static/css/mypage/reservation.css, src/main/resources/templates/faq/notice.html, src/main/resources/templates/main/main.html, src/main/resources/templates/mypage/inquiry.html
화이트라벨대신 커스텀에러페이지 출력
<br/>
#153
<br/>
<br/>
<br/>
=> [FEATURE][ERRORPAGEAPPLY]에러페이지 적용

src/main/java/com/ohgiraffers/washplan/reservation/controller/ReservationController.java, src/main/java/com/ohgiraffers/washplan/reservation/model/dao/ReservationMapper.java, src/main/java/com/ohgiraffers/washplan/reservation/model/service/QRCodeService.java, src/main/java/com/ohgiraffers/washplan/reservation/model/service/ReservationService.java, src/main/resources/mappers/ReservationMapper.xml, src/main/resources/templates/reservation/reservation.html
예약을하고 큐알코드를 스캔하게 되면 해당기기가 사용중으로 바뀌고
만약 예약시작시간에서 10분안에 큐알스캔을 하지않으면 자동취소가 되고 해당 유저의 자동취소횟수가 늘어납니다.
<br/>
#151 
<br/>
<br/>
<br/>
=> [FEATURE][QR-FIX] 큐알코드 수정

src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/resources/mappers/InquiryMapper.xml, src/main/resources/static/css/admin/admin.css, src/main/resources/static/css/admin/adminInquiry.css, src/main/resources/static/css/admin/adminMachine.css, src/main/resources/static/css/admin/adminNotice.css, src/main/resources/static/css/admin/adminUser.css, src/main/resources/templates/admin/admin.html, src/main/resources/templates/admin/admininquiry.html, src/main/resources/templates/admin/adminmachine.html, src/main/resources/templates/admin/adminnotice.html, src/main/resources/templates/admin/adminuser.html, src/main/resources/templates/main/main.html, src/main/resources/templates/reservation/reservation.html
지도 마커 유지, 홈페이지 이름 수정, 기기 상태변경 모달창 수정, 공지 작성 수정, 공지 삭제 후 리스트 새로고침, 예약창 건조기 옵션 이름 수정, 기기 추가 후 예약페이지 모달 창 수정
<br/>
#156 
<br/>
<br/>
<br/>
=> [FIX][ALL-FIX] 전체적인 수정

src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/resources/static/css/mypage/reservation.css, src/main/resources/templates/admin/admininquiry.html, src/main/resources/templates/admin/adminmachine.html, src/main/resources/templates/admin/adminnotice.html, src/main/resources/templates/admin/adminuser.html, src/main/resources/templates/auth/findid.html, src/main/resources/templates/auth/findpwd.html, src/main/resources/templates/auth/forget.html, src/main/resources/templates/auth/login.html, src/main/resources/templates/auth/reset.html, src/main/resources/templates/signup/agree.html, src/main/resources/templates/signup/email.html, src/main/resources/templates/signup/signup.html
아침에 말한거 수정
<br/>
#159 
<br/>
<br/>
<br/>
=> [FIX][NAVQR]수정

src/main/java/com/ohgiraffers/washplan/reservation/model/service/QRCodeService.java, src/main/java/com/ohgiraffers/washplan/reservation/model/service/ReservationService.java, src/main/java/com/ohgiraffers/washplan/user/controller/MyPageController.java, src/main/resources/mappers/MyPageMapper.xml, src/main/resources/mappers/ReservationMapper.xml, src/main/resources/static/css/mypage/reservation.css, src/main/resources/templates/main/main.html, src/main/resources/templates/mypage/reservation.html, src/main/resources/templates/reservation/reservation.html
마이페이지에서도 큐알을 스캔하게 되면 사용중으로 바뀌게 수정하였습니다.
<br/>
#158 
<br/>
<br/>
<br/>
=> [FIX][QR-FIX2] 큐알 수정

src/main/java/com/ohgiraffers/washplan/admin/controller/AdminController.java, src/main/java/com/ohgiraffers/washplan/admin/model/dao/AdminMapper.java, src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/java/com/ohgiraffers/washplan/config/SecurityConfig.java, src/main/java/com/ohgiraffers/washplan/reservation/controller/ReservationController.java, src/main/java/com/ohgiraffers/washplan/reservation/model/service/ReservationService.java, src/main/resources/mappers/AdminMapper.xml, src/main/resources/mappers/ReservationMapper.xml, src/main/resources/static/css/admin/adminMachine.css, src/main/resources/static/css/reservation/reservation.css, src/main/resources/templates/admin/admin.html, src/main/resources/templates/admin/admininquiry.html, src/main/resources/templates/admin/adminmachine.html, src/main/resources/templates/admin/adminnotice.html, src/main/resources/templates/admin/adminuser.html, src/main/resources/templates/faq/faq.html, src/main/resources/templates/faq/notice.html, src/main/resources/templates/main/main.html, src/main/resources/templates/reservation/reservation.html
관리자 탭 수정, 스크롤 추가
<br/>
#163 
<br/>
<br/>
<br/>
=> [FIX][ADMIN-FIX] 관리자 수정

src/main/java/com/ohgiraffers/washplan/admin/controller/AdminController.java, src/main/java/com/ohgiraffers/washplan/admin/model/dao/AdminMapper.java, src/main/java/com/ohgiraffers/washplan/admin/model/service/AdminService.java, src/main/resources/mappers/AdminMapper.xml, src/main/resources/static/css/admin/admin.css, src/main/resources/static/css/admin/adminInquiry.css, src/main/resources/static/css/admin/adminMachine.css, src/main/resources/static/css/admin/adminNotice.css, src/main/resources/static/css/admin/adminUser.css, src/main/resources/static/css/reservation/reservation.css, src/main/resources/templates/admin/adminuser.html, src/main/resources/templates/reservation/reservation.html
관리자 css 수정, 관리자 유저 활성화버튼 구현
<br/>
#167 
<br/>
<br/>
<br/>
=> [FEATURE][ADMIN-CSS-FIX]관리자 CSS 수정

src/main/java/com/ohgiraffers/washplan/notice/controller/NoticeController.java, src/main/java/com/ohgiraffers/washplan/notice/model/dao/NoticeMapper.java, src/main/java/com/ohgiraffers/washplan/notice/model/service/NoticeService.java, src/main/resources/mappers/NoticeMapper.xml, src/main/resources/static/css/faq/faq.css, src/main/resources/static/css/faq/notice.css, src/main/resources/static/css/mypage/inquiry.css, src/main/resources/static/css/mypage/mypage.css, src/main/resources/static/css/signup/signup.css, src/main/resources/templates/faq/faq.html, src/main/resources/templates/faq/notice.html, src/main/resources/templates/mypage/mypage.html, src/main/resources/templates/signup/signup.html
윈도우 수정사항
<br/>
#166
<br/>
<br/>
<br/>
=> [FIX][CSSFIX]수정사항

src/main/resources/static/css/faq/notice.css, src/main/resources/static/css/mypage/inquiry.css, src/main/resources/static/css/mypage/reservation.css, src/main/resources/static/css/signup/signup.css, src/main/resources/templates/faq/notice.html, src/main/resources/templates/mypage/inquiry.html
누락된거 수정
<br/>
#170
<br/>
<br/>
<br/>
=> [FIX][FIXFIX]누락 수정

src/main/java/com/ohgiraffers/washplan/auth/controller/EmailController.java, src/main/resources/static/css/faq/faq.css, src/main/resources/static/css/faq/notice.css, src/main/resources/static/css/reservation/reservation.css, src/main/resources/templates/faq/faq.html, src/main/resources/templates/faq/notice.html, src/main/resources/templates/reservation/reservation.html
faq/예약에서도 마이페이지 누를시 재확인창 뜨게 변경/ 이메일 인증코드 문구 변경
<br/>
#172
<br/>
<br/>
<br/>
=> [FIX][MYPAGEFIX]마이페이지 nav 수정

src/main/java/com/ohgiraffers/washplan/reservation/model/dao/ReservationMapper.java, src/main/java/com/ohgiraffers/washplan/reservation/model/service/ReservationService.java, src/main/resources/mappers/ReservationMapper.xml, src/main/resources/static/css/admin/admin.css, src/main/resources/static/css/admin/adminInquiry.css, src/main/resources/static/css/admin/adminMachine.css, src/main/resources/static/css/admin/adminNotice.css, src/main/resources/static/css/admin/adminUser.css, src/main/resources/templates/admin/adminnotice.html
관리자 탭,모달,작성 수정 자동취소 스케듈러 추가
<br/>
#173 
<br/>
<br/>
<br/>
=> [FIX][ADMIN-FIX]관리자 수정
